# Generated by Django 4.1.7 on 2023-03-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseNo', models.TextField()),
                ('nameOfDriver', models.TextField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
